messages/messages.json, src/commands/force/lightning/test/create.ts, src/generators/lightningTestGenerator.ts, src/templates/lightningtest/DefaultLightningTest.resource, src/templates/lightningtest/_staticresource.resource-meta.xml, test/commands/lightning/test/create.test.ts
This PR adds the `sfdx force:lightning:test:create` command
@W-6783783@
=> Add Lightning Test Create command

COMMANDS.md, README.md
Fix links for commands in README and add force:lightning:test command
W-6820293
=> Fix links for commands in README

README.md
Fix force:lightning:test:create link in readme
W-6820293
=> Fix force:lightning:test:create link

messages/messages.json, src/commands/force/project/create.ts, src/generators/projectGenerator.ts, test/commands/project/create.test.ts
Adds the missing login url attribute to project create. I'm still working on the tests but want to get an early review on the fix.
=> Loginurl attribute fix for project create

src/commands/force/project/create.ts, src/generators/projectGenerator.ts, src/templates/project/analytics/Manifest.xml, src/templates/project/empty/Manifest.xml, src/templates/project/sfdx-project.json, src/templates/project/standard/Manifest.xml
Ports #47 to master branch.
(cherry picked from commit 97fee2f5050245741d89ccc4feaff207f405a639)
=> Port #47 to master branch

test/utils/createUtil.test.ts
Fixes test failures in Windows environments
@W-6884420@
=> Fix windows test failure

test/utils/createUtil.test.ts
Porting windows test fixes to the develop branch
@W-6884420@
=> Fix Windows test failure (#50)

.vscode/settings.json, src/commands/force/lightning/component/create.ts, src/generators/lightningComponentGenerator.ts, src/templates/lightningcomponent/lwc/DefaultLightningLWC.js, test/commands/force/lightning/component/create.test.ts, test/commands/lightning/component/create.test.ts
This PR ports fixes #52 & #54 to the `develop` branch
@W-6930289@
=> Port LWC fixes to develop

src/templates/project/gitignore
Adds jsconfig.json to gitignore as it changes every time you create an new LWC.
=> Adds jsconfig.json to gitignore

.github/autointegrator.yml
Add config file for autointegrator bot
=> Autointegrator config

README.md, src/commands/force/project/create.ts
@W-6491472@ (#61)
(cherry picked from commit 546fa045d1838e66c3a4ca789fe2370eceeda1fc)
Show correct default directory for sfdx force:project:create --help
W-6491472
=> Show correct default directory for project creation help

src/commands/force/analytics/template/create.ts, src/commands/force/apex/class/create.ts, src/commands/force/apex/trigger/create.ts, src/commands/force/lightning/app/create.ts, src/commands/force/lightning/component/create.ts, src/commands/force/lightning/event/create.ts, src/commands/force/lightning/interface/create.ts, src/commands/force/lightning/test/create.ts, src/commands/force/visualforce/component/create.ts, src/commands/force/visualforce/page/create.ts
Update the default outputdir for all commands to give accurate help text
W-7123399
=> Update default outputdir for all commands to '.'

messages/messages.json, src/commands/force/analytics/template/create.ts, src/commands/force/apex/class/create.ts, src/commands/force/apex/trigger/create.ts, src/commands/force/lightning/app/create.ts, src/commands/force/lightning/component/create.ts, src/commands/force/lightning/event/create.ts, src/commands/force/lightning/interface/create.ts, src/commands/force/lightning/test/create.ts, src/commands/force/visualforce/component/create.ts, src/commands/force/visualforce/page/create.ts, src/generators/analyticsTemplateGenerator.ts, src/templates/analytics/waveTemplates/DefaultAnalyticsTemplate/app-to-template-rules.json, src/templates/analytics/waveTemplates/DefaultAnalyticsTemplate/dashboards/basicDashboard.json, src/templates/analytics/waveTemplates/DefaultAnalyticsTemplate/folder.json, src/templates/analytics/waveTemplates/DefaultAnalyticsTemplate/releaseNotes.html, src/templates/analytics/waveTemplates/DefaultAnalyticsTemplate/template-info.json, src/templates/analytics/waveTemplates/DefaultAnalyticsTemplate/template-to-app-rules.json, src/templates/analytics/waveTemplates/DefaultAnalyticsTemplate/ui.json, src/templates/analytics/waveTemplates/DefaultAnalyticsTemplate/variables.json, test/commands/force/analytics/template/create.test.ts
Ports #75 to develop. 75 involved a change to the analytics template command, which is missing in the develop branch and had to manually be resolved. This will need to be ported to pre-release as well.
=> Port #75 to develop and add missing analytics template command to develop branch

package.json
- Make postpack script cross platform by using shx
@W-6450724@
=> Use shx in postpack

src/generators/projectGenerator.ts, src/templates/project/.eslintignore, src/templates/project/.prettierignore, src/templates/project/gitignore, src/templates/project/package.json, test/commands/project/create.test.ts
Adds package.json to default project
@W-7236780@
=> added package.json to project

.circleci/config.yml, .nycrc, package.json, scripts/remove-lib.js
- Add build/test job for windows
- Process and upload code coverage
@W-7129488@
=> Windows build/test using CircleCI

.github/CODEOWNERS
Enables code owners
@W-7268572@
=> Enable code owners

package.json, src/templates/analytics/waveTemplates/DefaultAnalyticsTemplate/app-to-template-rules.json, src/templates/analytics/waveTemplates/DefaultAnalyticsTemplate/dashboards/basicDashboard.json, src/templates/analytics/waveTemplates/DefaultAnalyticsTemplate/folder.json, src/templates/analytics/waveTemplates/DefaultAnalyticsTemplate/template-info.json, src/templates/analytics/waveTemplates/DefaultAnalyticsTemplate/template-to-app-rules.json, src/templates/analytics/waveTemplates/DefaultAnalyticsTemplate/ui.json, src/templates/analytics/waveTemplates/DefaultAnalyticsTemplate/variables.json, test/commands/force/analytics/template/create.test.ts
- remove undocumented `storedQueries` field from sample template-info.json
- format sample template files to match default prettier format
- add oclif topic description for force:analytics and force:analytics:template
- W-7258830 (storedQueries)
- W-7222866 (topic description)
=> force:analytics updates

src/generators/projectGenerator.ts, src/templates/project/.eslintignore, src/templates/project/.prettierignore, src/templates/project/gitignore, src/templates/project/package.json, test/commands/project/create.test.ts
* Added package.json to project
* Updated ignored files
Co-authored-by: Brian Buchanan <bbuchanan@salesforce.com>
=> added package.json to project (#42)

.circleci/config.yml, package.json
Updates package.json and circleci config to run on node 10.x and above.
@W-7431049@
=> Update project to run on node 10.15.0 or above

.vscode/launch.json, command-snapshot.json, package.json, src/utils/logger.ts, src/utils/messageUtil.ts, yarn.lock
Adds tests for command reference generation and deprecation to catch issues at dev and CI time v.s. CLI publish time.
@W-7319588@
=> test: add command reference and deprication tests

.vscode/launch.json, command-snapshot.json, package.json, src/generators/projectGenerator.ts, src/utils/logger.ts, src/utils/messageUtil.ts, yarn.lock
=> test: add command reference and deprication tests (#116)

src/generators/analyticsTemplateGenerator.ts, src/generators/apexClassGenerator.ts, src/generators/apexTriggerGenerator.ts, src/generators/lightningAppGenerator.ts, src/generators/lightningComponentGenerator.ts, src/generators/lightningEventGenerator.ts, src/generators/lightningInterfaceGenerator.ts, src/generators/lightningTestGenerator.ts, src/generators/projectGenerator.ts, src/generators/visualforceComponentGenerator.ts, src/generators/visualforcePageGenerator.ts, src/utils/templateCommand.ts, test/commands/project/create.test.ts
Updates how we import certain dependencies. Fixes issues surfaced by the import bringing type information.
@W-7481028@
=> Update imports and issues related with types

.git2gus/config.json
Adds git2gus config. This is needed to sync PR commits as changelists in GUS work item.
W-7251867
=> Add Git2Gus config

src/generators/projectGenerator.ts, src/templates/project/.eslintignore, src/templates/project/.eslintrc.json, src/templates/project/aura.eslintrc.json, src/templates/project/lwc.eslintrc.json, src/templates/project/package.json, test/commands/project/create.test.ts
Adds eslint config and scripts for aura
@W-7634995@
=> Added eslint config for aura

src/generators/apexClassGenerator.ts, src/generators/apexTriggerGenerator.ts, src/generators/lightningAppGenerator.ts, src/generators/lightningComponentGenerator.ts, src/generators/lightningEventGenerator.ts, src/generators/lightningInterfaceGenerator.ts, src/generators/lightningTestGenerator.ts, src/generators/projectGenerator.ts, src/generators/visualforceComponentGenerator.ts, src/generators/visualforcePageGenerator.ts
Porting a PR #121  from develop branch
@W-7481052@
=> remove conflicter references (#121)

src/commands/force/apex/trigger/create.ts
Fixes an issue with the example for `apex:trigger:create`
@W-7776467@
=> Doc fix for apex:trigger:create example

src/templates/project/package.json
Updates node devDependencies for new projects.
Fixes #150
=> Bumped node dependencies for project template

src/templates/project/.eslintignore, src/templates/project/.prettierignore
Added missing standard resources to `.eslintignore` and `.prettierignore` ignore files.
Fixes #152
=> Added missing resources to ignore files

SECURITY.md
=> Add security doc

.circleci/config.yml
Use global git config (local config needs to checkout repo first) for publishing job
=> Fix git config

.circleci/config.yml
=> Fix persist workspace config

.circleci/config.yml, .vscode/tasks.json
Fix ssh config for deploy, add a task to publish custom version.
=> ssh config fix

.circleci/config.yml, lerna.json, packages/plugin-templates/.gitignore, packages/plugin-templates/package.json, packages/templates/package.json
port `49.4.3` and circle config changes
=> port main to dev

packages/templates/src/generators/sfdxGenerator.ts, packages/templates/src/service/templateService.ts
Expose getDefaultApiVersion; fix outputDir to be relative to `cwd` set in `TemplateService`
=> Template Service update

packages/templates/src/generators/sfdxGenerator.ts, packages/templates/src/service/templateService.ts
Release template service updates in `49.4.4`
@W-8005573@
=> Port #194 to main

lerna.json, packages/plugin-templates/package.json, packages/templates/package.json
Port 49.4.4 release to develop
=> Port 49.4.4 release to develop

.vscode/launch.json, CONTRIBUTING.md, README.md, contributing/coding-guidelines.md, contributing/commit-guidelines.md, contributing/developing.md, packages/plugin-templates/README.md
Updates contributing docs. Fixes "Run All Tests" script
@W-7922058@
=> Update contribution guide

packages/templates/src/templates/project/aura.eslintrc.json, packages/templates/src/templates/project/lwc.eslintrc.json
Port #186 (Before monorepo refactor) to develop
=> Port #186 to develop

.circleci/config.yml, lerna.json, package.json, packages/plugin-templates/yarn.lock, packages/templates/src/templates/project/package.json, packages/templates/test/service/templateService.test.ts
- Fix lint issues
- Enforce lint in CircleCI test jobs
- Add volta configuration
- Add oclif plugin link/unlink scripts on top level package.json
@W-8017763@
=> Update dev scripts

lerna.json, packages/plugin-templates/package.json, packages/templates/package.json
=> Updated version 49.9.1

.github/dependabot.yml, lerna.json, packages/plugin-templates/package.json, packages/templates/package.json
=> Port 49.9.0 to develop

packages/plugin-templates/test/commands/force/analytics/template/create.test.ts, packages/templates/src/templates/analytics/waveTemplates/DefaultAnalyticsTemplate/dashboards/basicDashboard.json, packages/templates/src/templates/analytics/waveTemplates/DefaultAnalyticsTemplate/template-info.json
Port changes for release 49.9.2
=> Port changes for release v49.9.2

lerna.json, packages/plugin-templates/package.json, packages/templates/package.json
=> Port changes for 49.10.0 to Develop

.commitlintrc.json, .vscode/tasks.json, CONTRIBUTING.md, README.md, package.json, yarn.lock
Implements commitizen for commit format enforcement.
@W-8165492@
=> chore: implement commitizen for commit format enforcement

packages/plugin-templates/messages/messages.json, packages/plugin-templates/test/commands/project/create.test.ts, packages/templates/src/templates/project/analytics/README.md, packages/templates/src/templates/project/empty/README.md, packages/templates/src/templates/project/standard/README.md
Updates the 3 project:create readmes for analytics, standard, empty
Reduce maintenance and overhead by removing duplicate documentation
https://gus.lightning.force.com/lightning/r/ADM_Work__c/a07B0000008g3ZhIAI/view
=> Ekapner readme updates

.circleci/config.yml, .commitlintrc.json, .vscode/tasks.json, CONTRIBUTING.md, README.md, lerna.json, package.json, packages/plugin-templates/messages/messages.json, packages/plugin-templates/package.json, packages/plugin-templates/test/commands/project/create.test.ts, packages/templates/package.json, packages/templates/src/templates/project/analytics/README.md, packages/templates/src/templates/project/empty/README.md, packages/templates/src/templates/project/gitignore, packages/templates/src/templates/project/standard/README.md, packages/templates/src/utils/types.ts, packages/templates/test/generators/sfdxGenerator.test.ts, packages/templates/test/service/templateService.test.ts, yarn.lock
Porting changes for release 50.1.0
=> Port v50.1.0

lerna.json, packages/plugin-templates/package.json, packages/templates/package.json
Port version update to develop
=> chore: updated version 50.1.0

.gitignore, packages/plugin-templates/command-snapshot.json, packages/plugin-templates/messages/messages.json, packages/plugin-templates/package.json, packages/plugin-templates/src/commands/force/staticresource/create.ts, packages/plugin-templates/test/commands/force/staticresource/create.test.ts, packages/templates/package.json, packages/templates/src/generators/staticResourceGenerator.ts, packages/templates/src/i18n/i18n.ts, packages/templates/src/templates/staticresource/_gitkeep, packages/templates/src/templates/staticresource/_staticresource.resource-meta.xml, packages/templates/src/templates/staticresource/empty.css, packages/templates/src/templates/staticresource/empty.js, packages/templates/src/templates/staticresource/empty.json, packages/templates/src/templates/staticresource/empty.resource, packages/templates/src/templates/staticresource/empty.txt, packages/templates/src/utils/types.ts, packages/templates/yarn.lock
Port of PR #192 , it includes some additional changes.
@W-8044464@
=> Create staticresource develop

.gitignore, packages/plugin-templates/command-snapshot.json, packages/plugin-templates/messages/messages.json, packages/plugin-templates/package.json, packages/plugin-templates/src/commands/force/staticresource/create.ts, packages/plugin-templates/test/commands/force/staticresource/create.test.ts, packages/templates/package.json, packages/templates/src/generators/staticResourceGenerator.ts, packages/templates/src/i18n/i18n.ts, packages/templates/src/templates/staticresource/_gitkeep, packages/templates/src/templates/staticresource/_staticresource.resource-meta.xml, packages/templates/src/templates/staticresource/empty.css, packages/templates/src/templates/staticresource/empty.js, packages/templates/src/templates/staticresource/empty.json, packages/templates/src/templates/staticresource/empty.resource, packages/templates/src/templates/staticresource/empty.txt, packages/templates/src/utils/types.ts, packages/templates/yarn.lock
=> Port 50.2.0 changes to main

.circleci/config.yml, .gitignore, lerna.json, packages/plugin-templates/package.json, packages/templates/package.json
Porting today's release commits back to develop branch
=> port main release commits

.vscode/tasks.json, contributing/publishing.md, scripts/port-changes.js
1. Adds port-pr script.
2. Adds publishing documentation (this is mostly a copy of the SDR publishing doc).
@W-8383744@
=> chore: add port-pr script and publishing doc

packages/templates/src/templates/project/extensions.json
Adds Lana extension as recommended.
=> Add lana to recommended extensions

packages/plugin-templates/test/commands/force/apex/class/create.test.ts, packages/templates/test/service/templateService.test.ts
Fixes broken test resulting from #245
Failing test.
=> updated apex template test

.circleci/config.yml, .gitignore, .vscode/tasks.json, contributing/publishing.md, packages/plugin-templates/test/commands/force/apex/class/create.test.ts, packages/templates/src/templates/apexclass/DefaultApexClass.cls, packages/templates/src/templates/project/extensions.json, packages/templates/test/service/templateService.test.ts, scripts/port-changes.js
=> Port v50.5.0

lerna.json, packages/plugin-templates/package.json, packages/templates/package.json
Port version update to develop
=> chore: updated version 50.6.0

packages/plugin-templates/package.json, packages/plugin-templates/yarn.lock, packages/templates/package.json, packages/templates/yarn.lock
Update @salesforce/core to 2.13.0
@W-8871930@
=> chore: update @salesforce/core to 2.13.0

packages/plugin-templates/package.json, packages/plugin-templates/yarn.lock, packages/templates/package.json, packages/templates/yarn.lock
=> Port PR for release v50.7.0

lerna.json, package.json, packages/plugin-templates/package.json, packages/templates/package.json, packages/templates/test/generators/sfdxGenerator.test.ts, packages/templates/test/service/templateService.test.ts
Updating the default api version to 51.0
@W-8881435@
=> feat: update default api version to v51.0

lerna.json, package.json, packages/plugin-templates/package.json, packages/templates/package.json, packages/templates/test/generators/sfdxGenerator.test.ts, packages/templates/test/service/templateService.test.ts
Porting changes for release 51.0.0
=> Port pr v51.0.0

packages/templates/src/templates/project/analytics/ScratchDef.json, packages/templates/src/templates/project/standard/ScratchDef.json
update scratchDef for v51 api changes
@W-8904232@
=> fix: v51 setPassword is a feature

packages/templates/src/templates/project/analytics/ScratchDef.json, packages/templates/src/templates/project/standard/ScratchDef.json
=> Port PR for release v51.2.0

lerna.json, packages/plugin-templates/package.json, packages/templates/package.json
Version bump for release v51.2.0
=> chore: updated version 51.2.0

packages/plugin-templates/test/commands/force/apex/class/create.test.ts, packages/templates/src/templates/apexclass/DefaultApexClass.cls, packages/templates/test/service/templateService.test.ts
Port commits from develop to main.
=> chore: port PR for version 51.3.0

lerna.json, packages/plugin-templates/package.json, packages/templates/package.json
=> chore: updated version 51.3.0

packages/plugin-templates/package.json, packages/plugin-templates/yarn.lock, packages/templates/package.json, packages/templates/yarn.lock
bump @salesforce/core to 2.23.2
=> bump @salesforce/core to2.23.2

lerna.json, packages/plugin-templates/package.json, packages/templates/package.json
=> chore: updated version 51.5.0 (#337)

lerna.json, packages/plugin-templates/package.json, packages/templates/package.json, packages/templates/test/generators/sfdxGenerator.test.ts, packages/templates/test/service/templateService.test.ts
update default api version to v52.0
@W-9466031@
=> feat: update default api version to v52.0

lerna.json, packages/plugin-templates/package.json, packages/templates/package.json, packages/templates/test/generators/sfdxGenerator.test.ts, packages/templates/test/service/templateService.test.ts
Port to main for releasing v52.0.0
=> Port v52.0.0

.circleci/config.yml, .vscode/tasks.json, contributing/publishing.md, packages/plugin-templates/test/commands/project/create.test.ts, packages/templates/src/generators/projectGenerator.ts, packages/templates/src/templates/project/.husky/pre-commit, packages/templates/src/templates/project/package.json
=> Port pr v52.1.0

lerna.json, packages/plugin-templates/package.json, packages/templates/package.json
=> Port v52.1.0 to develop

packages/templates/src/templates/project/.husky/pre-commit
Updates the Husky pre-commit hook template and fixes issue https://github.com/forcedotcom/cli/issues/1108
https://github.com/forcedotcom/cli/issues/1108
=> fix: husky pre-commit hook template

.circleci/config.yml
fix dist tags issue - wait for version to become available on NPM registry.
@W-9357574@
=> fix: fix dist tags issue

OSSREADME.json, packages/templates/package.json, packages/templates/src/generators/analyticsTemplateGenerator.ts, packages/templates/src/generators/apexClassGenerator.ts, packages/templates/src/generators/apexTriggerGenerator.ts, packages/templates/src/generators/lightningAppGenerator.ts, packages/templates/src/generators/lightningComponentGenerator.ts, packages/templates/src/generators/lightningEventGenerator.ts, packages/templates/src/generators/lightningInterfaceGenerator.ts, packages/templates/src/generators/lightningTestGenerator.ts, packages/templates/src/generators/projectGenerator.ts, packages/templates/src/generators/sfdxGenerator.ts, packages/templates/src/generators/staticResourceGenerator.ts, packages/templates/src/generators/visualforceComponentGenerator.ts, packages/templates/src/generators/visualforcePageGenerator.ts, packages/templates/src/i18n/i18n.ts, packages/templates/src/service/gitRepoUtils.ts, packages/templates/src/service/templateService.ts, packages/templates/test/custom-templates/apexclass/DefaultApexClass.cls, packages/templates/test/custom-templates/apexclass/_class.cls-meta.xml, packages/templates/test/service/templateService.test.ts, packages/templates/yarn.lock
=> Implement custom templates in template library

packages/templates/test/service/templateService.test.ts
Update the temporary test branch (so that PR passed the build before merging) to develop
=> chore: update test branch to develop

packages/plugin-templates/package.json, packages/plugin-templates/yarn.lock, packages/templates/package.json, packages/templates/yarn.lock
Update @salesforce/core to 2.28.0
@W-9955035@
=> chore: update sfdx-core

lerna.json, packages/plugin-templates/package.json, packages/templates/package.json, packages/templates/src/templates/project/gitignore
=> Port to Develop v52.2.0

.circleci/config.yml, lerna.json, packages/plugin-templates/package.json, packages/plugin-templates/yarn.lock, packages/templates/package.json, packages/templates/yarn.lock
=> Port pr v52.3.0

.circleci/config.yml
Fix bump package version script
=> fix: fix config script

packages/plugin-templates/src/utils/templateCommand.ts, packages/plugin-templates/test/utils/templateCommand.test.ts
=> Port pr v52.4.0

.circleci/config.yml, .vscode/tasks.json, contributing/developing.md, contributing/publishing.md
Publish as part of every merge to main
@W-10054133@
=> chore: changes to publish as part of every merge to main @W-10054133@

.eslintrc.json, .vscode/tasks.json, package.json, packages/plugin-templates/.eslintrc.json, packages/plugin-templates/package.json, packages/plugin-templates/src/index.ts, packages/plugin-templates/src/utils/index.ts, packages/plugin-templates/test/commands/force/lightning/component/create.test.ts, packages/plugin-templates/tslint.json, packages/templates/.eslintrc.json, packages/templates/package.json, packages/templates/src/generators/lightningComponentGenerator.ts, packages/templates/src/i18n/i18n.ts, packages/templates/src/i18n/localization.ts, packages/templates/src/service/gitRepoUtils.ts, packages/templates/src/service/templateService.ts, packages/templates/src/utils/adapter.ts, packages/templates/src/utils/index.ts, packages/templates/src/utils/logger.ts, packages/templates/tslint.json, packages/templates/yarn.lock, tslint.json, yarn.lock
This change removes TSLint and replaces it with ESLint.
@W-7210928@
=> chore: migrate from TSLint to ESLint @W-7210928@

.circleci/config.yml, .eslintrc.json, .github/CODEOWNERS, .vscode/tasks.json, contributing/developing.md, contributing/publishing.md, package.json, packages/plugin-templates/.eslintrc.json, packages/plugin-templates/package.json, packages/plugin-templates/src/index.ts, packages/plugin-templates/src/utils/index.ts, packages/plugin-templates/test/commands/force/lightning/component/create.test.ts, packages/plugin-templates/tslint.json, packages/templates/.eslintrc.json, packages/templates/package.json, packages/templates/src/generators/lightningComponentGenerator.ts, packages/templates/src/i18n/i18n.ts, packages/templates/src/i18n/localization.ts, packages/templates/src/service/gitRepoUtils.ts, packages/templates/src/service/templateService.ts, packages/templates/src/templates/project/lwc.eslintrc.json, packages/templates/src/utils/adapter.ts, packages/templates/src/utils/index.ts, packages/templates/src/utils/logger.ts, packages/templates/src/utils/types.ts, packages/templates/tslint.json, packages/templates/yarn.lock, tslint.json, yarn.lock
=> Port pr v52.5.0

.circleci/config.yml, packages/plugin-templates/test/utils/templateCommand.test.ts, packages/templates/test/service/templateService.test.ts
Removes the backport changes to develop
No more develop branch. This step is not required.
=> fix: remove backport changes @W-10054133@

packages/plugin-templates/package.json, packages/plugin-templates/yarn.lock, packages/templates/package.json, packages/templates/yarn.lock
Updates sfdx-cli for security and performance purposes.
@W-8858092@
=> chore: bump sfdx-core version

packages/plugin-templates/package.json, packages/plugin-templates/test/commands/force/analytics/template/create.test.ts, packages/plugin-templates/test/commands/force/apex/class/create.test.ts, packages/plugin-templates/test/commands/force/apex/trigger/create.test.ts, packages/plugin-templates/test/commands/force/lightning/app/create.test.ts, packages/plugin-templates/test/commands/force/lightning/component/create.test.ts, packages/plugin-templates/test/commands/force/lightning/event/create.test.ts, packages/plugin-templates/test/commands/force/lightning/interface/create.test.ts, packages/plugin-templates/test/commands/force/staticresource/create.test.ts, packages/plugin-templates/test/commands/force/visualforce/component/create.test.ts, packages/plugin-templates/test/commands/force/visualforce/page/create.test.ts, packages/plugin-templates/test/commands/lightning/app/create.test.ts, packages/plugin-templates/test/commands/lightning/component/create.test.ts, packages/plugin-templates/test/commands/lightning/event/create.test.ts, packages/plugin-templates/test/commands/lightning/interface/create.test.ts, packages/plugin-templates/test/commands/lightning/test/create.test.ts, packages/plugin-templates/test/commands/project/create.test.ts, packages/plugin-templates/test/utils/templateCommand.test.ts, packages/plugin-templates/yarn.lock
Bump the Salesforce command library to remove dependency on sfdx-faye.
=> chore: bump salesforce command

packages/plugin-templates/package.json, packages/plugin-templates/yarn.lock, packages/templates/package.json, packages/templates/yarn.lock
Allow our core dependency to keep up with small changes as needed
=> perf: move core to a careted version

packages/plugin-templates/package.json, packages/plugin-templates/yarn.lock, packages/templates/package.json, packages/templates/yarn.lock
=> chore: update yeoman

.circleci/config.yml
Use context to define all environment variables
@W-10539922@
=> chore: use context for env variables

lerna.json, packages/plugin-templates/package.json, packages/templates/package.json, packages/templates/test/generators/sfdxGenerator.test.ts
- Increase API version to 54
Review note: see [previous](https://github.com/forcedotcom/salesforcedx-templates/pull/408/files) PR for reference.
=> chore: increment major api version to 54

README.md, packages/templates/src/utils/createUtil.ts, packages/templates/yarn.lock
- remove unused yeoman environment dependency from create utils
-  fix broken link to commands doc
@W-10832373@
=> build: remove unused yeoman environment dependency from create utils

.circleci/config.yml, lerna.json, packages/templates/test/generators/sfdxGenerator.test.ts
Update context values used in circleci build. 
@W-11372105@
=> build: update circleci context values for new npm context and altered TIDE context

package.json, test/generators/sfdxGenerator.test.ts
Bumps templates to the latest major version
@W-11969892@
=> feat: increment major api version to 56

.github/workflows/failureNotification.yml, .github/workflows/manualRelease.yml, .github/workflows/onPushToMain.yml, .github/workflows/onRelease.yml, .github/workflows/test.yml, .github/workflows/unitTestsLinux.yml, .github/workflows/unitTestsWindows.yml, .github/workflows/validatePR.yml
Cleans up the workflow naming conventions a la the [same](https://github.com/forcedotcom/salesforcedx-vscode/pull/4574) update in vs code.
Follow up to #527
=> fix: clean up workflow setup

package.json
Bump the default API version to 57. 
@W-12471619@
=> fix: update SF api version for major release

package.json
Bump the default API version to 58.
@W-13502462@
=> chore: update SF api version for major release

package.json, yarn.lock
=> fix(deps): use current kit

.github/workflows/slackNotification.yml
Updates title and file name for the slack notification workflow
[skip-validate-pr]
=> Update slack notification workflow name

package.json, yarn.lock
bumps salesforce core to 5.3.20
@W-11622957@
=> fix: bump core to 5.3.20

.github/workflows/releaseWithCoreBundle.yml
Add a workflow to publish templates-bundle that uses core-bundle in order to be consumed by vsce.
@W-15288752@
=> chore: add workflow

.github/workflows/releaseWithCoreBundle.yml
fix: inherit the secrets for the next workflow to consume
@W-15288752@
=> fix: inherit the secrets for the next workflow to consume

.github/workflows/releaseWithCoreBundle.yml, .github/workflows/test.yml, .github/workflows/testWithCoreBundle.yml, package.json, test/generators/sfdxGenerator.test.ts, test/service/templateService.test.ts, yarn.lock
Implement automation tests with core-bundle.
@W-15634782@
Test run: https://github.com/forcedotcom/salesforcedx-templates/actions/runs/9306715518/job/25616476594?pr=583 ✅
=> chore: automation test for core bundle

.github/workflows/releaseWithCoreBundle.yml
Changes condition to publish bundled version
@W-15634782@
=> chore: release bundled version after real publish and not gh release

package.json, yarn.lock
bump template version to 61 (250)
bumps core version to align with vscode
@W-15476622@
=> feat!: build v 61 of templates

package.json, yarn.lock
Uses v8 of the @salesforce/core dependency.
@W-16083844@
=> feat: bump @salesforce/core from v7 to v8

README.md, package.json, src/generators/baseGenerator.ts, src/utils/constants.json, test/generators/baseGenerator.test.ts, yarn.lock
In last release, the structure of lib folder in the library has changed, which makes the module 61.4.2 invalid. This PR fixes the issue by keeping the original structure.
@W-15736930@
=> fix: keep the structure of lib folder

README.md, src/generators/baseGenerator.ts, src/utils/constants.json, src/utils/constants.ts, test/generators/baseGenerator.test.ts, yarn.lock
@W-16407766@
remove the constants.json file in favor of exported const for api version
=> fix: move default api version to a constant

package.json, src/utils/constants.ts
Bumps `DEFAULT_API_VERSION` to `63.0`.
@W-17722121@
=> [W-17722121] feat: update the api version to v63

contributing/coding-guidelines.md, src/i18n/localization.ts, src/utils/createUtil.ts, test/utils/createUtil.test.ts
removes leftover tslint comments
@W-7775683@
=> W-7775683 chore: remove tslint comments

src/templates/lightningcomponent/lwc/default/__tests__/default.test.js, src/templates/lightningcomponent/lwc/typeScript/__tests__/typeScript.test.ts, src/templates/project/package.json
fixes import in lwc test
@W-15275731@, https://github.com/forcedotcom/salesforcedx-vscode/issues/5510
=> fix: W-15275731 - fix import in lwc test

package.json, src/utils/constants.ts
Bumps DEFAULT_API_VERSION to 64.0.
[@W-18684311@](https://gus.lightning.force.com/lightning/r/ADM_Work__c/a07EE00002FSvc9YAD/view)
=> [W-18684311] feat: update the api version to v64

package.json, src/utils/constants.ts
Bumps DEFAULT_API_VERSION to 65.0.
@W-19704215@
=> [W-19704215] feat: update the api version to v65
