src/commands/force/project/create.ts, src/generators/projectGenerator.ts, src/templates/project/analytics/Manifest.xml, src/templates/project/empty/Manifest.xml, src/templates/project/sfdx-project.json, src/templates/project/standard/Manifest.xml
Updates project:create to use the api version method to get the version instead of relying on the hardcoded value 47.0.
W-6825719
=> Project create to use defaultApiVersion method for setting version

src/commands/force/lightning/component/create.ts, src/generators/lightningComponentGenerator.ts, test/commands/lightning/component/create.test.ts
Update LWC generation so that only the filenames are camelCased, while the class name stays consistent with what the user enters for the name flag.
=> Ensure LWC class name is the same as the value passed with the name flag

.vscode/settings.json, src/commands/force/lightning/component/create.ts, src/generators/lightningComponentGenerator.ts, src/templates/lightningcomponent/lwc/DefaultLightningLWC.js, test/commands/force/lightning/component/create.test.ts, test/commands/lightning/component/create.test.ts
Follow up to PR #52 to address scenarios where `--componentname` value is camelCase and js class name should be pascal case.
#53  , @W-6902712@
=> LWC js class name should always be pascal case

src/commands/force/lightning/event/create.ts
Fixes a typo in one of the examples for lightning:event:create
W-6826538
=> Fix example typo for lightning event

src/commands/force/lightning/event/create.ts
(cherry picked from commit 9267b22523b9e63fcdbad24454a8cdeb69128bdd)
=> [Port #58] Fix example typo for lightning event

src/generators/apexClassGenerator.ts, src/generators/apexTriggerGenerator.ts, src/generators/lightningAppGenerator.ts, src/generators/lightningComponentGenerator.ts, src/generators/lightningEventGenerator.ts, src/generators/lightningInterfaceGenerator.ts, src/generators/lightningTestGenerator.ts, src/generators/projectGenerator.ts, src/generators/visualforceComponentGenerator.ts, src/generators/visualforcePageGenerator.ts
This PR removes all references to the conflicter. The conflicter was originally referenced to ensure that the generator recognizes when there is a conflict but does not give the user a prompt before overwriting any files that conflict with pre-existing files. Now, the default behavior by yeoman is our desired behavior (recognize & overwrite without prompt) so there is no need to reference the conflicter.
If we want to change this behavior in the future, we would have to create a new Conflicter class and set our desired behavior.
@W-7481052@
=> Remove references to conflicter

src/templates/analytics/waveTemplates/DefaultAnalyticsTemplate/dashboards/basicDashboard.json, src/templates/analytics/waveTemplates/DefaultAnalyticsTemplate/template-info.json, src/templates/project/analytics/ScratchDef.json, test/commands/force/analytics/template/create.test.ts, test/commands/project/create.test.ts
- Add the dev productivity settings (from #110) to the analytics project scratch-def.json
- Hardcode the assetVersion in the analytics to 48.0 to match the format of the dashboard in the template
- Include the `_tp` name suffix on the sample analytics template dashboard, to support it being used in multiple embedded analytics app in the server
=> Updates for analytics project and sample template

package.json, yarn.lock
This PR addresses the issues of requiring Node to be installed locally for the end user and creating an empty .yo-repository folder in the directory the command was run from. It looks like this issue was introduced by Yeoman release 2.8.1 as an experimental feature. This PR reverts the version of Yeoman back down to the latest one we had previously released with the plugin.
We've reached out to yeoman on this issue here: https://github.com/yeoman/environment/issues/227
@W-7554801@
=> Fix for node requirement & .yo-repository directory generation

src/templates/project/standard/account.soql
The semi-colon isnt needed when you select and run the query.
@W-7654878@
=> Removed semicolon on soql example

src/utils/templateCommand.ts, test/utils/createUtil.test.ts
Allows users to specify api versions by either using `SFDX_API_VERSION` env var or setting the `apiVersion` via `sfdx force:config:set`
N/A
=> Allow api version to be set by config

package.json
Update the version to v49 after R2
=> chore: update to v49

.circleci/config.yml
Adding github to authenticated host, since we didn't `checkout` in the job where we pushes the git tags
https://circleci.com/docs/2.0/gh-bb-integration/#establishing-the-authenticity-of-an-ssh-host
=> add known host config

src/templates/project/aura.eslintrc.json, src/templates/project/lwc.eslintrc.json
Disabled several eslint rules to reduce the noise on common aura code including default samples.
@W-7982322@
=> Change default eslint rules to reduce warnings on new code

packages/plugin-templates/yarn.lock
Remove @salesforce/templates from yarn.lock to prevent getting the code from npm when developing the repo
@W-8017763@
=> Remove @salesforce/templates

packages/plugin-templates/test/commands/force/analytics/template/create.test.ts, packages/templates/src/templates/analytics/waveTemplates/DefaultAnalyticsTemplate/dashboards/basicDashboard.json, packages/templates/src/templates/analytics/waveTemplates/DefaultAnalyticsTemplate/template-info.json
In 49.0, the json for analytics dashboards changed a bit. Now that all customers
have been on 49.0 for awhile, this updates the sample analytics template to the
new format.
=> Update analytics dashboard json format

.circleci/config.yml
Restricts approval access for circle ci workflows. Only members of the GitHub Team 'PDT' should be able to approve workflows for publishing.
@W-8165486@
=> chore: add context restriction for publish-workflow

packages/templates/src/templates/project/gitignore
This PR will add a new query-results directory to the .gitignore of the project template.
As part of the new soql query builder extension, customers will be able to save results from a soql query to the disk however we don't anticipate they will want to check in those results to source control by default.
@W-8136966@
=> JHork: Add query-results to .gitignore

.circleci/config.yml
1. Adds 'unless' clause for commit-workflow so we are not running multiple test jobs during publish.
2. Updates npm-release-management-orb version.
3. Adds new commands for gh-config and create-git-tag (this command was removed from the npm-release-management-orb).
@W-8211855@
=> chore: update npm release management orb

.circleci/config.yml, .gitignore
Update CircleCI to publish the library package without using `npm-release-management` orb
@W-8384687@
=> fix: publish library module without using orb

packages/templates/src/templates/apexclass/DefaultApexClass.cls
Changes the default apex class template to use inherited sharing
closes #244
=> refactor: switch to inherited sharing

packages/plugin-templates/test/commands/force/apex/class/create.test.ts, packages/templates/src/templates/apexclass/DefaultApexClass.cls, packages/templates/test/service/templateService.test.ts
After discussing this internally we've decided to revert back to using `with sharing`
@W-8926389@
=> fix: revert back to using with sharing on Apex

packages/templates/src/templates/project/gitignore
The SOQL extension no longer creates a `query-results` directory for users when they save query data as csv or json.
So we dont need to include the directory in the `gitignore`
=> fix: remove reference to query-results directory

README.md, packages/plugin-templates/test/commands/project/create.test.ts, packages/templates/src/generators/projectGenerator.ts, packages/templates/src/templates/project/sfdx-project.json
Adds a `name` field to sfdx-project.json for use by the new Functions product
https://gus.lightning.force.com/lightning/r/ADM_Work__c/a07AH0000009lOcYAI/view
=> feat: add project name to generator

packages/plugin-templates/yarn.lock, packages/templates/yarn.lock
Upgrades schema dependency to 1.1.0. This is necessary to bring in change https://github.com/forcedotcom/schemas/pull/35, which is needed for #296.
=> chore: upgrade yarn.lock dependency for schemas

contributing/publishing.md
Adds additional information about semvar for release duty.
=> docs: add semvar info to publishing doc

lerna.json, packages/plugin-templates/package.json, packages/plugin-templates/yarn.lock, packages/templates/package.json
manually bump main version to 51.4.0
https://app.circleci.com/pipelines/github/forcedotcom/salesforcedx-templates/953/workflows/ca0e8422-e6f8-465b-a9fe-86d758fc34b0/jobs/3534/parallel-runs/0/steps/0-116
`sfdx-trust plugins:trust:verify --npm $PKG_NAME@$PKG_VERSION --json` failed with `NpmTagNotFound`. might be occasional
=> chore: updated version 51.4.0

lerna.json, packages/plugin-templates/package.json, packages/templates/package.json
"The dist tag was not found" error (W-9357574) blocked the version bump step in CI.
Manually bump main version.
=> chore: updated version 51.5.0

packages/templates/src/templates/project/aura.eslintrc.json, packages/templates/src/templates/project/lwc.eslintrc.json, packages/templates/src/templates/project/package.json
Following feedback from @pmdartus, this PR on the project template
- Merges the two linting scripts (Aura and LWC) into a single one
- Gets rid of `eslint-config-prettier` because it is not needed
=> Simplified linting scripts and reduced dependencies

packages/plugin-templates/test/commands/force/lightning/component/create.test.ts, packages/templates/src/generators/lightningComponentGenerator.ts, packages/templates/src/templates/lightningcomponent/lwc/analyticsDashboard/analyticsDashboard.js-meta.xml, packages/templates/src/templates/lightningcomponent/lwc/analyticsDashboardWithStep/analyticsDashboardWithStep.js-meta.xml
Set the `<masterLabel>` in the .js-meta.xml for analytics dashboard lwcs, defaulting to a title case of the file name (e.g. fooWithStep -> Foo With Step).
@W-9889592@
cc: @jimmydief
=> fix: add default masterLabel to analytics lwcs

packages/templates/src/templates/project/gitignore
Adds `.sf/` and `deploy-options.json` to the `.gitignore` that will be generated by `sf generate project`.
[The `name` property in `sfdx-project.json` was already added by @cafreeman](https://github.com/forcedotcom/salesforcedx-templates/blame/develop/packages/templates/src/templates/project/sfdx-project.json#L8).
@W-9789875@
=> feat: add .sf/ and deploy-options.json to project .gitignore

.circleci/config.yml
Change circleci node version from 10 to 14
Fixes an issue to switch to eslint from tslint. With this fix, this PR can be merged - https://github.com/forcedotcom/salesforcedx-templates/pull/389
=> fix: change circleci node version from 10 to 14

lerna.json, packages/plugin-templates/package.json, packages/templates/package.json, packages/templates/test/generators/sfdxGenerator.test.ts
Bump `pjson` version so that templates are created using `sourceApiVersion` equal to `53`
@W-10169202@
=> chore: bump version to 53

packages/templates/src/templates/project/package.json
After creating a project using `sfdx force:project:create --projectname=newproject`, this error message appears on `npm install` in the project folder:
```
npm ERR! code ETARGET
npm ERR! notarget No matching version found for prettier-plugin-apex@^1.10.1.
npm ERR! notarget In most cases you or one of your dependencies are requesting
npm ERR! notarget a package version that doesn't exist.
npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/benjaminloerincz/.npm/_logs/2021-12-23T14_17_36_183Z-debug-0.log
```
This PR changes the version number for prettier-plugin-apex.
- [394](https://github.com/forcedotcom/salesforcedx-templates/issues/394)
- [398](https://github.com/forcedotcom/salesforcedx-templates/issues/398)
- @W-10527954@
=> Downgrade prettier-plugin-apex

packages/plugin-templates/test/commands/force/lightning/component/create.test.ts, packages/templates/src/templates/lightningcomponent/lwc/analyticsDashboard/analyticsDashboard.js, packages/templates/src/templates/lightningcomponent/lwc/analyticsDashboardWithStep/analyticsDashboardWithStep.js
This was added to the server api in Spring '22 (54.0), just updating the lwc template to include it.
=> fix: add refresh api hook to dashboard lwcs

.eslintrc.json, lerna.json, package.json, packages/plugin-templates/.eslintrc.json, packages/plugin-templates/package.json, packages/plugin-templates/tsconfig.json, packages/plugin-templates/yarn.lock, packages/templates/.eslintrc.json, packages/templates/package.json, packages/templates/src/generators/projectGenerator.ts, packages/templates/src/generators/sfdxGenerator.ts, packages/templates/src/service/templateService.ts, packages/templates/src/utils/adapter.ts, packages/templates/src/utils/logger.ts, packages/templates/test/generators/sfdxGenerator.test.ts, packages/templates/test/service/templateService.test.ts, packages/templates/test/utils/logger.test.ts, packages/templates/yarn.lock
Update Yeoman Generator and Yeoman environment to latest versions.  
Update shx.
Update code to account for breaking changes in yeoman and convert the logger to meet the requirements of the yeoman adapter.
=> fix: update yeoman & shx to address high dependabot alerts.

packages/plugin-templates/test/commands/force/lightning/component/create.test.ts, packages/templates/src/templates/lightningcomponent/lwc/analyticsDashboard/analyticsDashboard.js, packages/templates/src/templates/lightningcomponent/lwc/analyticsDashboardWithStep/analyticsDashboardWithStep.js
Adds `stateChangedCallback()` to dashboard lwcs. It's new in Summer '22
@W-11111405@
=> fix: add `stateChangedCallback()` to dashboard lwcs

packages/templates/src/index.ts
"SFDX: Create Lightning Web Component" is using CreateUtil to ensure new component names following the lightning component naming rules. This PR exports CreateUtil so other commands like "SFDX: Rename Component" can also leverage the functions for guarding user input for a new component name. 
[#4145](https://github.com/forcedotcom/salesforcedx-vscode/pull/4145)
=> chore: export CreateUtil

.circleci/config.yml
Removes the unnecessary listing of the git tags so that auto publish jobs will complete. 
Found when publish was attempted: https://app.circleci.com/pipelines/github/forcedotcom/salesforcedx-templates/1589/workflows/1600396c-c065-4125-8c7a-28cf09f1ad31/jobs/6155
=> chore: remove listing git tags so publish will not fail

.git2gus/config.json, .github/workflows/manualRelease.yml, contributing/publishing.md, package.json, src/service/templateService.ts, test/generators/sfdxGenerator.test.ts
Changes where we derive the default Salesforce API version. Previously we were conflating the version of the package with the Salesforce API version, so we could not benefit from semantic versioning. In order to keep our CI simple and benefit from semantic versioning, this will separate these two values. 
Going forward with the code as it is here, the only value that will need to change during major Salesforce version updates is the `salesforceApiVersion` in the `package.json`. The version should no longer be directly touched, as the `conventional-changelog` will update this as needed. 
A better longer term solution would be to dynamically generate this value, but this would require some understanding of what "default" should mean.
This PR also updates the `publishing.md` documentation to …
=> refactor: change the location of the default api version

src/templates/project/package.json
bumps @salesforce/sfdx-lwc-jest to 3.1.0 so that module jest-environment-jsdom is installed
Bumps other dev deps to latest version
@W-14512085@ [#5239](https://github.com/forcedotcom/salesforcedx-vscode/issues/5239)
=> fix: bump dep for @salesforce/sfdx-lwc-jest to 3.1.0

.github/workflows/onRelease.yml, package.json, yarn.lock
sfdx-core is only used to import `Global` so this shouldn't be a breaking change (no Connection, testSetup, SfError, etc).  See https://github.com/forcedotcom/sfdx-core/blob/main/MIGRATING_V6-V7.md for change info
@W-15387805@
=> fix: update salesforce/core

src/generators/baseGenerator.ts
package.json cannot be bundled due to the previous usage. This PR makes package.json bundle-able, so core extension can use it seamlessly.
@W-15736930@
=> chore: make packageJson bundleable

.husky/pre-push, scripts/verify-for-bundling.js, src/generators/baseGenerator.ts
core extension needs to bundle the templates separately when bundling the module. This PR is to add a test before each push to make sure the folder /templates exists in /lib so that bundling templates within core extension will find the target artifacts.
@W-15736969@
=> test: verify templates is the same in lib and src before each push 

.github/dependabot.yml, src/templates/project/package.json
pin eslint to v8 for cli dependants since v8 is no longer minor releasing. dependabot does not look to comprehend ignoring major bump for eslint here. 
refer to #630 for more info.
[skip-validate-pr]
=> chore: pin eslint to v8 for cli dependants

src/templates/project/settings.json
Adds a config rule that excludes the content of the `.sf` folder from VSCode search (just like `.sfdx` is already ignored).
[skip-validate-pr]
=> feat: exclude .sf folder from search
